# Generated by Django 4.1.4 on 2022-12-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_autor_options_alter_autor_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='descripcion',
        ),
    ]
